package ru.virarnd.kommunalkin.common

const val INPUT_ERROR_CHECK_STATUS_NO_ERRORS = 0
const val INPUT_ERROR_CHECK_STATUS_EMPTY_FIELD = 1
const val INPUT_ERROR_CHECK_STATUS_UNKNOWN_TEXT = 2
const val INPUT_ERROR_CHECK_STATUS_NOT_SUITABLE = 3
const val INPUT_ERROR_CHECK_STATUS_DOES_NOT_MATCH = 4
const val INPUT_ERROR_CHECK_STATUS_ALREADY_EXIST = 5